### 登录账号
POST {{baseUrl}}/login
Accept: */*
Content-Type: application/json
Authorization: Bearer {{ token }}

{"account": "15082000855", "password": "123"}

> {% client.global.set("token", response.body.data); %}

### 请求产品信息
GET {{baseUrl}}/products
Accept: application/json
Authorization: Bearer {{ token }}

###
